### ISSUE TITLE
Wrong image Name in Json...

### ISSUE THREAD

**Issue by frischi** [allewun/ios-icon-generator#1]
Hi, this script works great. But I discovered one small issue:

In line 71:
  {
      "idiom" : "ipad",
      "size" : "40x40",
      "filename" : "Icon-40.png",
      "scale" : "1x"
    },

the "filename" : "Icon-40.png", should rather be a  "filename" : "Icon-Small-40.png",

After this change it works "smooth"...

Cheers,
Michael

**Comment by allewun** [comment]
Yeah I think you're right, thanks Michael. Fixed.
